{{/* Plantilla corregida para main-ingress/templates/ingress.yaml */}}
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: desarrollo
  annotations:
    # Anotación para que cert-manager sepa qué emisor de certificados usar
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Anotaciones personalizadas desde el archivo de valores (ej: ssl-redirect)
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  
  # La sección TLS debe estar aquí, dentro de spec:
  {{- if .Values.tls.enabled }}
  tls:
  - hosts:
      # Tomamos la lista completa de hosts del values.yaml
    {{- toYaml .Values.tls.hosts | nindent 6 }}
    secretName: {{ .Values.tls.secretName }}
  {{- end }}

  rules:
  # REGLA 1: Dominio Principal (ej: bytebuilders.software)
  - host: {{ .Values.paths.static_web.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.paths.static_web.serviceName }}
            port:
              number: {{ .Values.paths.static_web.servicePort }}

  # REGLA 2: Dominio WWW
  - host: www.{{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.paths.static_web.serviceName }}
            port:
              number: {{ .Values.paths.static_web.servicePort }}

  # REGLA 3: Subdominio para Panel
  - host: {{ .Values.paths.panel.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.paths.panel.serviceName }}
            port:
              number: {{ .Values.paths.panel.servicePort }}
    
  # REGLA 4: Subdominio para Airflow
  - host: {{ .Values.paths.airflow.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.paths.airflow.serviceName }}
            port:
              number: {{ .Values.paths.airflow.servicePort }}
{{- end }}