{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: desarrollo
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.paths.static_web.serviceName }}
            port:
              number: {{ .Values.paths.static_web.servicePort }}
      - path: /panel(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.paths.panel.serviceName }}
            port:
              number: {{ .Values.paths.panel.servicePort }}
      - path: /airflow(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.paths.airflow.serviceName }}
            port:
              number: {{ .Values.paths.airflow.servicePort }}
{{- end }}