# En: main-ingress/templates/ingress.yaml

{{- if .Values.ingress.enabled -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: desarrollo
  annotations:
    # Añadimos la anotación de cert-manager para que sepa qué emisor usar
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Asumo que usarás este nombre
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  {{- if .Values.tls.enabled }}
  tls:
  - hosts:
      # Tomamos la lista completa de hosts del values.yaml
    {{- toYaml .Values.tls.hosts | nindent 4 }}
    secretName: {{ .Values.tls.secretName }}
  {{- end }}
  rules:
  # REGLA 1: Dominio Principal (bytebuilders.software)
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: / # Siempre en la raíz
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.paths.static_web.serviceName }}
            port:
              number: {{ .Values.paths.static_web.servicePort }}

  # REGLA 2: Dominio WWW (www.bytebuilders.software)
  # Forma explícita y limpia de manejar 'www'
  - host: www.{{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.paths.static_web.serviceName }} # Apunta al mismo servicio
            port:
              number: {{ .Values.paths.static_web.servicePort }}

  # REGLA 3: Subdominio para Panel
  - host: {{ .Values.paths.panel.host }}
    http:
      paths:
      - path: / # Siempre en la raíz
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.paths.panel.serviceName }}
            port:
              number: {{ .Values.paths.panel.servicePort }}
    
  # REGLA 4: Subdominio para Airflow
  - host: {{ .Values.paths.airflow.host }}
    http:
      paths:
      - path: / # Siempre en la raíz
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.paths.airflow.serviceName }}
            port:
              number: {{ .Values.paths.airflow.servicePort }}
{{- end }}