# charts/main-ingress/templates/middlewares.yaml

# Middleware para quitar el prefijo /airflow
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-airflow-prefix
  namespace: desarrollo # Es buena práctica especificar el namespace
spec:
  stripPrefix:
    prefixes:
      - /airflow

---
# Middleware para quitar el prefijo /panel
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-panel-prefix
  namespace: desarrollo # Es buena práctica especificar el namespace
spec:
  stripPrefix:
    prefixes:
      - /panel