#replicas: 1

image:
  repository: ghcr.io/ml-for-academic-data/egi-dashboard
  pullPolicy: IfNotPresent
  tag: "default"

imagePullSecrets:
  - name: ghcr-credentials

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
