# --- values.yaml ---

replicas: 1

# El nombre de la aplicación, usado para labels y selectors
appName: frontend-dashboard

# El nombre del PersistentVolumeClaim que creamos para EFS
pvcName: efs-shared-pvc

image:
  repository: ghcr.io/ml-for-academic-data/egi-dashboard
  pullPolicy: IfNotPresent
  # El tag se puede seguir actualizando desde el pipeline de CI/CD
  tag: "default"

imagePullSecrets:
  - name: ghcr-credentials

# Configuración del servicio de red
service:
  # CAMBIO: Ahora es NodePort para que sea accesible desde fuera del clúster
  type: NodePort
  # Puerto que el servicio expone internamente en el clúster
  port: 5000
  # Puerto en el que la aplicación está escuchando dentro del contenedor
  containerPort: 5000