apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: egi-backend-pruebas
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ml-For-Academic-Data/egi-infrastructure-k8s.git
    path: charts/backend
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
        - values-pruebas.yaml # Usa los valores para pruebas
  destination:
    server: https://kubernetes.default.svc
    namespace: pruebas # Despliega en el namespace 'pruebas'
  syncPolicy: { automated: { prune: true, selfHeal: true }, syncOptions: ["CreateNamespace=true"] }
