apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-desarrollo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ml-For-Academic-Data/egi-infrastructure-k8s.git
    targetRevision: HEAD
    path: charts/main-ingress
    helm:
      # Puedes tener un values-desarrollo.yaml también para el ingress si lo necesitas
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: desarrollo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true