# En: applications/nginx-ingress-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.0
    helm:
      values: |
        controller:
          replicaCount: 1
          
          # Habilita y define el recurso IngressClass para que el controlador
          # gestione los Ingress que especifiquen `ingressClassName: nginx`.
          ingressClassResource:
            name: nginx
            enabled: true
            default: true

          # Permite que el controlador observe los Ingress en todos los namespaces.
          scope:
            enabled: true
          
          # Define el tipo de servicio del controlador.
          service:
            type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true