# En: applications/nginx-ingress-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.1
    helm:
      releaseName: nginx-ingress
      # --- SECCIÓN AÑADIDA ---
      # Estos valores le dicen al chart de NGINX cómo configurarse.
      values: |
        controller:
          # Esta línea es clave. Le dice al controller que procese
          # Ingresses incluso si no tienen una ingressClassName definida.
          # Aumenta la compatibilidad.
          watchIngressWithoutClass: true
          scope:
            # Habilita la configuración del scope (alcance)
            enabled: true
            # DEJAR VACÍO "" SIGNIFICA VIGILAR TODOS LOS NAMESPACES
            namespace: ""
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true