# En: applications/nginx-ingress-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.0
    helm:
      # --- SECCIÓN DE VALORES CORREGIDA Y SIMPLIFICADA ---
      values: |
        controller:
          # Para un solo nodo, 1 réplica es suficiente
          replicaCount: 1
          # Hacemos que el controller vigile todos los namespaces
          watchIngressWithoutClass: true
          scope:
            enabled: true
          # Especificamos explícitamente el tipo de servicio como NodePort
          service:
            type: NodePort
            # Ya no necesitamos las anotaciones de AWS
            # annotations: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true