tls:
  enabled: true
  secretName: produccion-tls # Un nombre de secret diferente para el certificado de producción
  hosts:
    - pr.bytebuilders.software
    - prpanel.bytebuilders.software
    - prairflow.bytebuilders.software
    - prapi.bytebuilders.software

paths:
  static_web:
    host: "pr.bytebuilders.software"
    serviceName: "egi-static-web-despliegue-service" # Asegúrate que el nombre del servicio sea el correcto para producción
    servicePort: 3000

  panel:
    host: "prpanel.bytebuilders.software"
    serviceName: "egi-frontend-despliegue-visualization-service"
    servicePort: 5000
  
  airflow:
    host: "prairflow.bytebuilders.software"
    serviceName: "backend-airflow-webserver-despliegue"
    servicePort: 8080