
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend-index.fullname" . }}-ingress # Genera un nombre único para el Ingress
  labels:
    {{- include "frontend-index.labels" . | nindent 4 }} # Aplica labels estándar del chart
  annotations:
    # Anotaciones específicas para el Nginx Ingress Controller
    # Asegúrate que tu Ingress Controller esté configurado para manejar estas anotaciones
    ingress.kubernetes.io/force-ssl-redirect: "true" # Opcional: Forzar redirección a HTTPS si tienes SSL
    nginx.ingress.kubernetes.io/proxy-body-size: "0" # Opcional: Permite cuerpos de solicitud de cualquier tamaño
    # IMPORTANTE: Si tus servicios internos (Airflow, Panel) NO esperan el path en la URL
    # (ej. si Airflow solo espera la raíz '/' pero lo expones en '/airflow'),
    # necesitarás un rewrite-target. Si las apps ya manejan el path completo, esto puede omitirse o ajustarse.
    # Para la app Flask (frontend-index) en la raíz, no se necesita rewrite para el path "/"
    # Para /airflow y /panel, el rewrite-target es común si las apps esperan la raíz.
    # Ejemplo si Airflow espera la raíz pero lo expones en /airflow:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx 
  rules:
    - host: {{ .Values.ingress.host | quote }} # El dominio que usarás, tomado de values.yaml
      http:
        paths:
          # --- Regla para el Frontend Index  ---
          - path: / # Expone la aplicación Flask en la raíz del dominio
            pathType: Prefix # Coincide con cualquier ruta que comience con '/'
            backend:
              service:
                name: {{ include "frontend-index.fullname" . }} # Nombre del servicio de K8s para tu frontend-index
                port:
                  number: {{ .Values.service.port }} # Puerto que expone el servicio (3000 por defecto)

          # --- Regla para Airflow (ej. accesible en your-ml-platform.com/airflow) ---
          # Se asume que Airflow tiene un servicio en Kubernetes llamado 'airflow-webserver-service'
          # Puedes obtener este nombre de tu chart de backend o de tu despliegue de Airflow.
          # Nota: el ($)(.*) captura el resto de la URL después de /airflow, para el rewrite-target.
          - path: /airflow(/|$)(.*) 
            pathType: Prefix
            backend:
              service:
                name: airflow-webserver-server # <<--- ¡IMPORTANTE! Reemplaza con el nombre REAL del Service de Airflow en tu clúster
                port:
                  number: 8080 # Puerto estándar de Airflow webserver

          # --- Regla para el Panel Dashboard (ej. accesible en your-ml-platform.com/panel) ---
          # Se asume que tu Dashboard tiene un servicio en Kubernetes llamado 'frontend-dashboard-service'
          # (Basado en el appName: frontend-dashboard de tu values.yaml del dashboard)
          - path: /panel(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-dashboard # <<--- ¡IMPORTANTE! Reemplaza con el nombre REAL del Service de tu Panel Dashboard
                port:
                  number: 5000 # Puerto que expone tu Panel Dashboard (según tu values.yaml adjunto)

  # --- Opcional: Configuración TLS para HTTPS ---
  # Si tienes un ClusterIssuer (ej. de cert-manager) para obtener certificados SSL
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "frontend-index.fullname" .)) }}
  {{- end }}