apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dashboard
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend-dashboard
  template:
    metadata:
      labels:
        app: frontend-dashboard
    spec:
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: dashboard
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          # --- AÑADIDO: Montaje del volumen para el container del frontend ---
          volumeMounts:
            - name: shared-data
              mountPath: /data # Montamos el EFS en una carpeta /data

      # --- AÑADIDO: Definición del volumen que se va a montar ---
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            # Usamos el MISMO PVC que el backend para acceder a los mismos datos
            claimName: efs-shared-pvc