apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dashboard
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend-dashboard
  template:
    metadata:
      labels:
        app: frontend-dashboard
    spec:
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: dashboard
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          # --- NUEVA SECCIÓN: MONTURA DE VOLUMEN ---
          volumeMounts:
            - name: shared-data
              # Montamos el disco en la misma ruta que tu código espera.
              mountPath: /opt/airflow/data
              # ¡Importante! El frontend solo necesita leer, no escribir.
              readOnly: true
      # --- NUEVA SECCIÓN: DEFINICIÓN DEL VOLUMEN ---
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-pvc
