apiVersion: v1
kind: Service
metadata:
  name: frontend-dashboard-service
spec:
  type: ClusterIP  
  selector:
    app: frontend-dashboard
  ports:
    - protocol: TCP
      port: 5006       
      targetPort: 5006