apiVersion: v1
kind: PersistentVolumeClaim # <-- Nota que el 'kind' (tipo) es PersistentVolumeClaim
metadata:
  name: efs-shared-pvc      # <-- Este es el nombre exacto que tus pods están buscando
  namespace: desarrollo      # Asegúrate de que esté en el namespace correcto
spec:
  accessModes:
    - ReadWriteMany        # <-- Debe coincidir con el modo de acceso del PV
  storageClassName: efs-sc # <-- Debe coincidir con el storageClassName del PV
  resources:
    requests:
      storage: 5Gi         # La cantidad de espacio que solicitas