apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-shared-pvc
  namespace: desarrollo # Importante: asegúrate de que esté en el namespace correcto
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi