# Plantilla para crear el secreto con la contraseña del usuario admin de Airflow.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.airflowAdmin.passwordSecretName }}
type: Opaque
stringData:
  # Puedes cambiar la contraseña aquí.
  # En un entorno de producción real, este valor podría venir
  # de un sistema de gestión de secretos externo.
  {{ .Values.airflowAdmin.passwordSecretKey }}: "admin1234"