apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-airflow-webserver
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend-airflow-webserver
  template:
    metadata:
      labels:
        app: backend-airflow-webserver
    spec:
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      
      # --- SECCIÓN CORREGIDA ---
      # El InitContainer ahora solo tiene las variables que necesita.
      initContainers:
      - name: airflow-db-init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["airflow", "db", "init"]
        env:
          - name: AIRFLOW__CORE__FERNET_KEY
            value: {{ .Values.airflow.fernetKey | quote }}
          - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            value: {{ .Values.airflow.dbConnection | quote }}
      
      # Contenedor principal del Webserver
      containers:
        - name: webserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["airflow", "webserver"]
          env:
            - name: AIRFLOW__CORE__FERNET_KEY
              value: {{ .Values.airflow.fernetKey | quote }}
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: {{ .Values.airflow.dbConnection | quote }}
            - name: AIRFLOW__CORE__EXECUTOR
              value: "SequentialExecutor"
            # Estas variables para crear el usuario están en el lugar correcto.
            - name: AIRFLOW__WWW__USER_CREATE
              value: "true"
            - name: AIRFLOW__WWW__USER_USERNAME
              value: {{ .Values.airflowAdmin.username | quote }}
            - name: AIRFLOW__WWW__USER_EMAIL
              value: {{ .Values.airflowAdmin.email | quote }}
            - name: AIRFLOW__WWW__USER_FIRSTNAME
              value: {{ .Values.airflowAdmin.firstName | quote }}
            - name: AIRFLOW__WWW__USER_LASTNAME
              value: {{ .Values.airflowAdmin.lastName | quote }}
            - name: AIRFLOW__WWW__USER_ROLE
              value: "Admin"
            - name: AIRFLOW__WWW__USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.airflowAdmin.passwordSecretName }}
                  key: {{ .Values.airflowAdmin.passwordSecretKey }}
          ports:
            - name: http
              containerPort: 8080 # Nota: El puerto interno del webserver es 8080, no 8793.
              protocol: TCP