apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.existingSecret }}
type: Opaque
stringData:
  # Esta contraseña debe ser manejada con cuidado.
  # En un entorno real, podría venir de un gestor de secretos externo.
  mysql-root-password: "rootpass"
  mysql-password: {{ .Values.mysql.password | quote }}