apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-airflow-scheduler
  template:
    metadata:
      labels:
        app: backend-airflow-scheduler
    spec:
      # --- SECCIÓN A AÑADIR/VERIFICAR ---
      # Le dice a este pod que use el secreto 'ghcr-credentials'
      # para descargar imágenes. La indentación aquí es CRUCIAL.
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      # --- FIN DE LA SECCIÓN ---
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["airflow", "scheduler"]
          env:
            - name: AIRFLOW__CORE__FERNET_KEY
              value: {{ .Values.airflow.fernetKey | quote }}
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: {{ .Values.airflow.dbConnection | quote }}
            - name: AIRFLOW__CORE__EXECUTOR
              value: "SequentialExecutor"
