apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-airflow-scheduler
spec:
  replicas: 1 # El scheduler siempre debe tener una sola réplica
  selector:
    matchLabels:
      app: backend-airflow-scheduler
  template:
    metadata:
      labels:
        app: backend-airflow-scheduler
    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["airflow", "scheduler"] # Comando para iniciar el scheduler
          env:
            - name: AIRFLOW__CORE__FERNET_KEY
              value: {{ .Values.airflow.fernetKey | quote }}
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: {{ .Values.airflow.dbConnection | quote }}
            - name: AIRFLOW__CORE__EXECUTOR
              value: "SequentialExecutor"