# Plantilla para el Servicio del Webserver de Airflow
apiVersion: v1
kind: Service
metadata:
  name: backend-airflow-webserver
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    # Este selector conecta el servicio con los pods creados por nuestro Deployment.
    app: backend-airflow-webserver
