apiVersion: v1
kind: Service
metadata:
  name: backend-airflow-webserver
# ... metadata ...
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8793          # <-- Cambiado para claridad
      targetPort: 8793    # <-- ¡ESTA ES LA CORRECCIÓN CRÍTICA!
      protocol: TCP
      name: http
  selector:
    app: airflow-webserver
    # ... etc ...