# Archivo de valores por defecto para el backend (Airflow)

# El número de réplicas por defecto para el webserver.
#replicas: 1

# Configuración de la imagen de Docker. Este valor es común a todos los
# componentes de Airflow (webserver y scheduler).
image:
  repository: ghcr.io/ml-for-academic-data/egi-backend
  pullPolicy: IfNotPresent
  # El tag será sobrescrito por los archivos de valores de cada ambiente.
  tag: 'c677e08'
# Nombre del secreto que contiene las credenciales para descargar la imagen.
imagePullSecrets:
  - name: ghcr-credentials
# Configuración común para todos los componentes de Airflow.
airflow:
  # La clave de encriptación de Airflow. Es crucial que sea la misma para todos los componentes.
  # DEBERÍAS cambiar este valor por uno generado por ti.
  fernetKey: "D_b7-k2tJcEmrfAPASL8V_cY03LJd-uWWtJ-8HN1Esk="
  # La conexión a la base de datos. Usamos el nombre del servicio de MySQL que crearemos.
  dbConnection: "mysql+pymysql://user:1234@mysql-server:3306/students"

# Configuración específica para el servicio del webserver.
# CORRECCIÓN: Renombrado de 'webserver_service' a 'service' para que coincida con la plantilla.
service:
  type: ClusterIP
  port: 8080

# Configuración para la base de datos MySQL.
mysql:
  image: mysql:8.0
  existingSecret: "mysql-credentials"
  database: "students"
  user: "user"
  password: "1234"
  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce

# --- NUEVA SECCIÓN ---
# Configuración del usuario administrador inicial de Airflow.
# Airflow creará este usuario automáticamente al arrancar si no existe.
airflowAdmin:
  # El nombre del secreto de Kubernetes que contendrá la contraseña.
  passwordSecretName: "airflow-admin-credentials"
  # La clave dentro del secreto que contiene la contraseña.
  passwordSecretKey: "admin-password"
  # Propiedades del usuario a crear.
  username: "admin"
  email: "admin@example.com"
  firstName: "Admin"
  lastName: "EGI"

resources: #Asignar mas recursos
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
