# Archivo de valores por defecto para el backend (Airflow)

replicas: 1

image:
  repository: ghcr.io/ml-for-academic-data/egi-backend
  pullPolicy: IfNotPresent
  tag: "default"

airflow:
  fernetKey: "D_b7-k2tJcEmrfAPASL8V_cY03LJd-uWWtJ-8HN1Esk="
  dbConnection: "mysql+mysqlclient://user:1234@mysql-server:3306/students"

webserver_service:
  type: ClusterIP
  port: 8080

mysql:
  image: mysql:8.0
  existingSecret: "mysql-credentials"
  database: "students"
  user: "user"
  password: "1234"
  # Nueva sección para la persistencia de datos de MySQL
  persistence:
    enabled: true
    # Solicita un volumen de 1GiB. En una nube real, esto provisionaría
    # un disco de almacenamiento automáticamente.
    size: 1Gi
    # El tipo de acceso. ReadWriteOnce es el más común.
    accessMode: ReadWriteOnce