# Archivo de valores por defecto para el backend (Airflow)

# El número de réplicas por defecto.
# Cada ambiente puede sobrescribir este valor si es necesario.
replicas: 1

# Configuración de la imagen de Docker que vamos a desplegar.
image:
  # El nombre de la imagen en el registry.
  # Este valor es común a todos los ambientes.
  repository: ghcr.io/ml-for-academic-data/egi-backend
  # La política de descarga.
  pullPolicy: IfNotPresent
  # La etiqueta de la imagen. Cada ambiente definirá su propia etiqueta
  # en su archivo de valores específico.
  tag: "default"

# Configuración del servicio que expondrá nuestra aplicación.
service:
  # El tipo de servicio por defecto.
  type: ClusterIP
  # El puerto en el que el servicio escuchará.
  port: 8080

# Aquí podríamos añadir más configuraciones comunes en el futuro.
# Por ejemplo, las variables de entorno de Airflow que sean
# iguales en todos los ambientes.
# airflow:
#   executor: "SequentialExecutor"