services:

  # Este es el nombre de tu servicio. Se usará como {{ $name }} en las plantillas.
  static-web: 
    # Esta bandera permite activar o desactivar el despliegue de este servicio.
    enabled: true 
    
    # La configuración de la imagen, que se leerá como {{ $service.image }}
    image:
      repository: ghcr.io/ml-for-academic-data/egi-static-web
      # El tag por defecto, se puede sobrescribir.
      tag: "9b2ca14" 
    
    # El puerto, que se leerá como {{ $service.port }}
    port: 3000 
    
    # El tipo de servicio, que se leerá como {{ $service.type }}
    type: ClusterIP

    env:
      AIRFLOW_URL: "http://54.204.172.139:32693"
      PANEL_URL: "http://54.204.172.139:30726"
