name: Generar Token para Pull de Imágenes

# 'workflow_dispatch' permite ejecutar este pipeline manualmente.
on:
  workflow_dispatch:
    inputs:
      # No necesitamos inputs, pero la sección es necesaria para que aparezca el botón.

jobs:
  generate-token:
    runs-on: ubuntu-latest
    permissions:
      # ¡Permiso clave! Le damos permiso para leer los paquetes de la organización.
      packages: read
    steps:
      - name: Generar Token de GitHub
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          # Le decimos que genere un token con los permisos que definimos arriba.
          # Este token será válido por 1 hora.
          app_id: ${{ secrets.YOUR_APP_ID }} # Necesitarás crear una GitHub App
          private_key: ${{ secrets.YOUR_APP_PRIVATE_KEY }}

      - name: Mostrar el Token
        run: |
          echo "Este token es válido por 1 hora. Úsalo para actualizar tu imagePullSecret en Kubernetes."
          echo "======================================================================================"
          echo ${{ steps.generate_token.outputs.token }}
          echo "======================================================================================"

